---
- name: create user
  hosts: devserver
  remote_user: vagrant
  become: yes
  become_method: sudo

  vars:
    password: $1$ansible$72eg2Nt0WeveaObTpx8bL0

  vars_prompt:
    - name: "username"
      prompt: "enter username"
      private: no

  roles: 
    - useradd
